### ISSUE TITLE
drawEM installation

### ISSUE THREAD

**Issue by nnashka** [MIRTK/DrawEM#6] opened 2016-05-05 18:05 UTC
Hi,
I have been trying to install this module for the past couple of days and I am running into an issue, so I am hoping there is an easy fix to it :S
After changing the dependencies so that they fit the new MIRTK architecture (it is still dependent on ImageIO), I still cannot generate the project when I enable the drawEM module (I tried installing it with an older version of MIRTK and it still does not work).
I get:

CMake Error at CMake/Basis/TargetTools.cmake:1704 (_add_library):
   Cannot find source file:

/home/me/Codes/MIRTK/MIRTK/Packages/DrawEM/include/m
 irtk/mirtkBiasCorrection.h

   Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
   .hxx .in .txx
 Call Stack (most recent call first):
   CMake/Basis/TargetTools.cmake:2109 (add_library)
   CMake/Basis/TargetTools.cmake:1079 (basis_add_library_target)
   CMake/Modules/mirtkAddLibrary.cmake:52 (basis_add_library)
   Packages/DrawEM/src/CMakeLists.txt:64 (mirtk_add_library)

CMake Error: CMake can not determine linker language for target: LibDrawEM

 CMake Error in Packages/DrawEM/src/CMakeLists.txt:
   Exporting the target "LibDrawEM" is not allowed since its linker language
   cannot be determined

Do you have any idea how I could ix it?

Thanks!

**Comment by amakropoulos** [comment] 2016-05-06 08:56
Hi, 
Thank you for reporting that!
It seems there is a reorganisation of the code in MIRTK that also affects Draw-EM.
I'll look into that and let you know next week.

**Comment by schuhschuh** [comment] 2016-05-06 10:03
@amakropoulos Sorry I didn't open an issue for the needed changes when applying them to MIRTK. The `mirtk` source file name prefix is dropped in favor of a directory `include/mirtk/` subdirectory. Thus, the file in the error message would now be `include/mirtk/BiasCorrection.h`. Also remove the `mirtk` prefix from the source files in the `src/` directory. Include other MIRTK header files in a source file using the syntax `#include "mirtk/BiasCorrection.h`.

**Comment by amakropoulos** [comment] 2016-05-15 11:18
Hi, 
The problem is now fixed, sorry for the delay.
Please send if you have any additional problems!

**Closed as completed by amakropoulos** 2016-05-15 11:18 UTC

**Comment by nnashka** [comment] 2016-05-16 20:14
Thanks!
